# Generated by Django 3.1.3 on 2021-01-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210123_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_favotite',
            new_name='is_favorite',
        ),
    ]
